greek = {
    'lang': 'greek',
    'version': '1.0',
    'slot_type': 'word',
    'udnorm': 'NFD',
    'dir_struct': ['author', 'book', 'editor'],
    'sentence_delimit': ['.', ';'],
    'normalization': normalizer,
    'lemmatizer_path': '~/github/pthu/tei_to_tf/helpertools/data/lemmatizer.pickle', # needs to be a .py filename (without .py and without quotes) or a full .pickle path
    '': '',
    'attrib_errors': {
            '{http://www.w3.org/XML/1998/namespace}id': 'id',
            '{http://www.w3.org/XML/1998/namespace}lang': 'lang',
            'boo': 'book',
            'fo1otnote': 'footnote',
            'fo6tnote': 'footnote',
            'foo1tnote': 'footnote',
            'foodnote': 'footnote',
            'foonote': 'footnote',
            'footn2ote': 'footnote',
            'footno1te': 'footnote',
            'footno3te': 'footnote',
            'footnot': 'footnote',
            'footnot1e': 'footnote',
            'footnot2e': 'footnote',
            'footnote1': 'footnote',
            'footnote2': 'footnote',
            'footnte': 'footnote',
            'footnτote': 'footnote',
            'footote': 'footnote',
            'fotnote': 'footnote',
            'Τfootnote': 'footnote',
            'm5arginal': 'marginal',
            'margi4nal': 'marginal',
            'margial': 'marginal',
            'marginael': 'marginal',
            'marginai': 'marginal',
            'marginale': 'marginal',
            'marginalp': 'marginal',
            'marginapl': 'marginal',
            'marginaΕl': 'marginal',
            'marginaΣl': 'marginal',
            'marginl': 'marginal',
            'margipnal': 'marginal',
            'margnal': 'marginal',
            'margpinal': 'marginal',
            'marinalΑB': 'marginal',
            'marpginal': 'marginal',
            'märginal': 'marginal',
            ' chapter': 'chapter',
            ' section': 'section',
            'antistrohe': 'antistrophe',
            'chap0ter': 'chapter',
            'chapter1': 'chapter',
            'chapterer': 'chapter',
            'chapters': 'chapter',
            'chaptser': 'chapter',
            'chaspter': 'chapter',
            'ephymn.': 'ephymn',
            'sction': 'section',
            'sectionn': 'section',
            'setence': 'sentence',
            'setion': 'section',
            'secton': 'section',
            'subdsection': 'subsection',
            'subection': 'subsection',
            'pargraph': 'paragraph',
            },
}

latin = {

}
